- name: APT update cache
  apt: update_cache=yes

- name: APT Upgrade
  apt: upgrade=dist

- name: Add python preconditions
  apt: update_cache=yes
  apt: pkg=python-pycurl state=present

- name: Install git
  apt: pkg=git-core state=present

- name: Install curl
  apt: pkg=curl state=present